#!/bin/bash

echo "Current PHP version is $(php -v | grep "PHP [5-8]" | cut -d' ' -f 2)"
read -rp "Do you want to proceed? [y/n]: " CHOICE 
[[ ! "${CHOICE}" =~ ^[yY](es)?$ ]] && { echo "Ok, next time"; exit 1; }
for i in "$@"; do
  cd "$HOME/$i"
  if [[ ! -f "./wp-config.php" ]]; then
    echo "Skipped for ${PWD}"
  else
    CORE_VERSION=$(wp core version)
    rm -rf wp-includes wp-admin
    wp core download --version="$CORE_VERSION" --skip-content --force
    echo "Replaced for ${PWD}"
fi
cd
done
